import {
  Box,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  TextField,
  FormControlLabel,
  FormLabel,
  Radio,
  RadioGroup,
} from "@mui/material";
import { display } from "@mui/system";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { MobileDatePicker } from "@mui/x-date-pickers/MobileDatePicker";
import Head from "next/head";
import React from "react";
export default function ReporterForm() {
  const [value, setValue] = React.useState(new Date("2014-08-18T21:11:54"));

  const handleChange = (newValue) => {
    setValue(newValue);
  };
  const [nationality, setNationality] = React.useState();
  const [currentCountry, setCurrentCountry] = React.useState();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h5>Step 1/2</h5>
        <h2>Please tell us more about yourself.</h2>
        <h3>
          *<span style={{ float: "left" }}>Your name</span>
        </h3>
        <Box
          component="form"
          sx={{
            "& > :not(style)": { m: 1, width: "25ch" },
          }}
          noValidate
          autoComplete="off"
          style={{
            display: "flex",
            flexDirection: "row",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <TextField
            required
            id="reporter-first-name"
            label="First name"
            variant="outlined"
          />
          <TextField
            required
            id="reporter-last-name"
            label="Last name"
            variant="outlined"
          />
          <TextField
            id="reporter-traslated-name"
            label="Traslated name (Optional)"
            variant="outlined"
          />
        </Box>
        <h3>
          *<span style={{ float: "left" }}>Date of Birth</span>
        </h3>
        <LocalizationProvider dateAdapter={AdapterDateFns}>
          <MobileDatePicker
            label="Date of Birth"
            inputFormat="yyyy.MM.dd"
            value={value}
            onChange={handleChange}
            renderInput={(params) => <TextField {...params} />}
          />
        </LocalizationProvider>
        <h3>
          *<span style={{ float: "left" }}>Nationality</span>
        </h3>
        <FormControl fullWidth>
          <InputLabel id="demo-simple-select-label">Nationality</InputLabel>
          <Select
            labelId="demo-simple-select-label"
            id="demo-simple-select"
            value={nationality}
            label="Current Country of Residence"
            onChange={handleChange}
          >
            <MenuItem value={"Ukrainian"}>Ukrainian</MenuItem>
          </Select>
        </FormControl>
        <h3>
          *<span style={{ float: "left" }}>Current Country of Residence</span>
        </h3>
        <FormControl fullWidth>
          <InputLabel id="demo-simple-select-label">
            Current Country of Residence
          </InputLabel>
          <Select
            labelId="demo-simple-select-label"
            id="demo-simple-select"
            value={currentCountry}
            label="Current Country of Residence"
            onChange={handleChange}
          >
            <MenuItem value={"Ukraine"}>Ukraine</MenuItem>
          </Select>
        </FormControl>
        <h3>
          *<span style={{ float: "left" }}>Phone Number 1</span>
        </h3>
        <FormControl
          fullWidth
          style={{
            display: "flex",
            flexDirection: "row",
            justifyContent: "center",
            alignItems: "center",
            width: "75%",
          }}
        >
          <Select
            labelId="demo-simple-select-label"
            id="demo-simple-select"
            value={currentCountry}
            label="Country Code"
            onChange={handleChange}
            style={{ width: "4rem", textAlign: "left", justifyItems: "right" }}
          >
            <MenuItem value={"+380"}>+380</MenuItem>
          </Select>
          <TextField label="Number">Number</TextField>
        </FormControl>
        <h3>
          <span style={{ float: "left" }}>Phone Number 2</span>
        </h3>
        <FormControl
          fullWidth
          style={{
            display: "flex",
            flexDirection: "row",
            justifyContent: "center",
            alignItems: "center",
            width: "75%",
          }}
        >
          <Select
            labelId="demo-simple-select-label"
            id="demo-simple-select"
            value={currentCountry}
            label="Country Code"
            onChange={handleChange}
            style={{ width: "4rem", textAlign: "left", justifyItems: "right" }}
          >
            <MenuItem value={"+380"}>+380</MenuItem>
          </Select>
          <TextField label="Number">Number</TextField>
        </FormControl>
        <h3>
          <span style={{ float: "left" }}>Email</span>
        </h3>
        <TextField label="E-mail (optional)">Email</TextField>
        <h3>
          *<span style={{ float: "left" }}>Relationship</span>
        </h3>
        <FormControl>
          <RadioGroup
            row
            aria-labelledby="demo-radio-buttons-group-label"
            defaultValue="female"
            name="radio-buttons-group"
          >
            <FormControlLabel
              value="female"
              control={<Radio />}
              label="Parent/Guardian"
            />
            <FormControlLabel
              value="Sibling"
              control={<Radio />}
              label="Sibling"
            />
            {/* <FormControlLabel value="other" control={<Radio />} label="Other" /> */}
          </RadioGroup>
        </FormControl>
      </main>
    </div>
  );
}
