import {
    Box, FormControl,
    InputLabel, MenuItem, Select, TextField
} from "@mui/material";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { MobileDatePicker } from "@mui/x-date-pickers/MobileDatePicker";
import Head from "next/head";
import React from "react";
export default function ReporterForm() {
  const [value, setValue] = React.useState(new Date("2014-08-18T21:11:54"));

  const handleChange = (newValue) => {
    setValue(newValue);
  };
  const [nationality, setNationality] = React.useState();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h5>Step 1/2</h5>
        <h2>Please tell us more about yourself.</h2>
        <h3>
          *<span style={{ float: "left" }}>Your name</span>
        </h3>
        <Box
          component="form"
          sx={{
            "& > :not(style)": { m: 1, width: "25ch" },
          }}
          noValidate
          autoComplete="off"
        >
          <TextField
            required
            id="reporter-first-name"
            label="First name"
            variant="outlined"
          />
          <TextField
            required
            id="reporter-last-name"
            label="Last name"
            variant="outlined"
          />
          <TextField
            id="reporter-traslated-name"
            label="Traslated name (Optional)"
            variant="outlined"
          />
        </Box>
        <h3>
          *<span style={{ float: "left" }}>Date of Birth</span>
        </h3>
        <LocalizationProvider dateAdapter={AdapterDateFns}>
          <MobileDatePicker
            label="Date of Birth"
            inputFormat="yyyy.MM.dd"
            value={value}
            onChange={handleChange}
            renderInput={(params) => <TextField {...params} />}
          />
        </LocalizationProvider>
        <h3>
          *<span style={{ float: "left" }}>Nationality</span>
        </h3>
        <FormControl fullWidth>
          <InputLabel id="demo-simple-select-label">
            Nationality
          </InputLabel>
          <Select
            labelId="demo-simple-select-label"
            id="demo-simple-select"
            value={nationality}
            label="Current Country of Residence"
            onChange={handleChange}
          >
            <MenuItem value={"Ukrainian"}>Ukrainian</MenuItem>
          </Select>
        </FormControl>
        <h3>
          *<span style={{ float: "left" }}>Current Country of Residence</span>
        </h3>
        <FormControl fullWidth>
          <InputLabel id="demo-simple-select-label">
            Current Country of Residence
          </InputLabel>
          <Select
            labelId="demo-simple-select-label"
            id="demo-simple-select"
            value={nationality}
            label="Current Country of Residence"
            onChange={handleChange}
          >
            <MenuItem value={"Ukraine"}>Ukraine</MenuItem>
          </Select>
        </FormControl>
        <h3>
          *<span style={{ float: "left" }}>Phone Number</span>
        </h3>
      </main>
    </div>
  );
}
