import {
  Box,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  TextField,
  FormControlLabel,
  FormLabel,
  Radio,
  RadioGroup,
} from "@mui/material";
import { display } from "@mui/system";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { MobileDatePicker } from "@mui/x-date-pickers/MobileDatePicker";
import Head from "next/head";
import React from "react";
export default function ReporterForm() {
  const [value, setValue] = React.useState(new Date("2014-08-18T21:11:54"));

  const handleChange = (newValue) => {
    setValue(newValue);
  };
  const [nationality, setNationality] = React.useState();
  const [currentCountry, setCurrentCountry] = React.useState();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ marginLeft:18 }}>
        <h5>Step 1/2</h5>
        <h2>Please tell us more about yourself.</h2>
        <h3>
          *<span style={{ float: "left" }}>Your name</span>
        </h3>
        <Box
          component="form"
          // sx={{
          //   "& > :not(style)": { m: 1, width: "25ch" },
          // }}
          noValidate
          autoComplete="off"
          style={{
            alignItems: "flex-start",
          }}
        >
          <div style={{ flexDirection: 'row', display: 'flex' }}>
            <TextField
              required
              id="reporter-first-name"
              label="First Name"
              variant="outlined"
            />
            <TextField
              required
              id="reporter-last-name"
              label="Last Name"
              variant="outlined"
              style={{ marginLeft: 20 }}
            />
          </div>

          <div style={{ paddingTop: 10 }}>
            <TextField
              id="reporter-traslated-name"
              label="Translated Name (Optional)"
              variant="outlined"
              style={{ width: 470 }}
            />
          </div>
        </Box>
        <h3>
          *<span style={{ float: "left" }}>Date of Birth</span>
        </h3>
        <LocalizationProvider dateAdapter={AdapterDateFns}>
          <div>
            <MobileDatePicker
              label="Date of Birth"
              inputFormat="yyyy.MM.dd"
              value={value}
              onChange={handleChange}
              renderInput={(params) => <TextField {...params} />}
            />
          </div>
        </LocalizationProvider>
        <h3>
          *<span style={{ float: "left" }}>Nationality</span>
        </h3>
        <FormControl style={{ width: 500 }}>
          <InputLabel id="demo-simple-select-label">Nationality</InputLabel>
          <Select
            labelId="demo-simple-select-label"
            id="demo-simple-select"
            value={nationality}
            label="Current Country of Residence"
            onChange={handleChange}
          >
            <MenuItem value={"Ukrainian"}>Ukrainian</MenuItem>
          </Select>
        </FormControl>
        <h3>
          *<span style={{ float: "left" }}>Current Country of Residence</span>
        </h3>
        <FormControl style={{ width: 500 }}>
          <InputLabel id="demo-simple-select-label">
            Current Country of Residence
          </InputLabel>
          <Select
            labelId="demo-simple-select-label"
            id="demo-simple-select"
            value={currentCountry}
            label="Current Country of Residence"
            onChange={handleChange}
          >
            <MenuItem value={"Ukraine"}>Ukraine</MenuItem>
          </Select>
        </FormControl>

        <h3>
          *<span style={{ float: "left" }}>Phone Number 1</span>
        </h3>

        <FormControl
          fullWidth
          style={{
            display: "flex",
            flexDirection: "row",
            width: "75%",
          }}
        >
          <Select
            labelId="demo-simple-select-label"
            id="demo-simple-select"
            value={currentCountry}
            label="Country Code"
            onChange={handleChange}
            style={{ width: "4rem", textAlign: "left", justifyItems: "right" }}
          >
            <MenuItem value={"+380"}>+380</MenuItem>
          </Select>
          <TextField style={{ marginLeft: 10 }} label="Number">Number</TextField>
        </FormControl>

        <h3>
          <span style={{ float: "left" }}>Phone Number 2</span>
        </h3>
        
        <FormControl
          fullWidth
          style={{
            display: "flex",
            flexDirection: "row",
          }}
        >
          <Select
            labelId="demo-simple-select-label"
            id="demo-simple-select"
            value={currentCountry}
            label="Country Code"
            onChange={handleChange}
            style={{ width: "4rem", marginTop: 18 }}
          >
            <MenuItem value={"+380"}>+380</MenuItem>
          </Select>
          <TextField label="Number" style={{ marginLeft: 10, marginTop: 18 }}>Number</TextField>
        </FormControl>
        <h3>
          <span style={{ float: "left" }}>Email</span>
        </h3>

        <TextField label="E-mail (optional)">Email</TextField>
        
        <h3>
          *<span style={{ float: "left" }}>Relationship</span>
        </h3>
        <FormControl>
          <RadioGroup
            row
            aria-labelledby="demo-radio-buttons-group-label"
            defaultValue="female"
            name="radio-buttons-group"
          >
            <FormControlLabel
              value="female"
              control={<Radio />}
              label="Parent/Guardian"
            />
            <FormControlLabel
              value="Sibling"
              control={<Radio />}
              label="Sibling"
            />
          </RadioGroup>
        </FormControl>
      </main>
    </div>
  );
}
